### Invalid search does not cause segmentation fault
http://localhost:8080/search

### Search for all tasks
http://localhost:8080/search?key=

### Search for test task
http://localhost:8080/search

{
    "key": "test"
}

### Test Delete
DELETE http://localhost:8080/delete?id=test